package:
  name: highspy
  version: 1.11.0
  top-level:
    - highspy
source:
  url: https://files.pythonhosted.org/packages/source/h/highspy/highspy-1.11.0.tar.gz
  sha256: 771e58c076122d207ff1b19759c21d3227f0da5b80dfd89a4145681524969cef
requirements:
  run:
    - numpy
about:
  home: null
  PyPI: https://pypi.org/project/highspy
  summary: A thin set of pybind11 wrappers to HiGHS
  license: null
extra:
  recipe-maintainers:
    - airen1986
